spring:
  datasource:
    url: ${PROD_DB_PROPERTY_URL:jdbc:mysql://property-db-svc:3306/propertydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicExtractor: TRACE

RECOMENDATION_IA_URL: http://property-recommendation-engine-svc:5000
HEATMAP_SERVICE_URL: http://predictive-heatmaps-of-neighborhood-price-evolution-svc:5000
ML_PRICE_SUGGESTION_URL: http://ml-pricesuggestionmodel-svc:5000
USER_MANAGEMENT_SERVICE_URL: http://user-management-service-svc
