spring:
  datasource:
    url: ${PROD_DB_RENTAL-AGREEMENT_URL:jdbc:mysql://rental-agreement-db-svc:3306/rental_agreement_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Kamouss@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

PROPERTY_SERVICE_URL: http://property-microservice-svc
TENANT_SCORING_IA_MODEL_URL: http://tenant-risk-scoring-svc:5000